# Generated by Django 6.0.1 on 2026-01-22 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the station is available for use')),
                ('is_occupied', models.BooleanField(default=False, help_text='Whether a charging session is in progress')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('current_voltage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('current_amperage', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('current_power', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_energy', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('current_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_power_factor', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charging Station',
                'verbose_name_plural': 'Charging Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_energy_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_energy_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('energy_consumed_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped_no_credit', 'Stopped - No Credit'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stations.chargingstation')),
            ],
            options={
                'verbose_name': 'Charging Session',
                'verbose_name_plural': 'Charging Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
